name: Constitutional Compliance Validation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  constitutional-compliance:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run TypeScript type checking
      run: npx tsc --noEmit
    
    - name: Build application
      run: npm run build
    
    - name: Validate Service Boundaries
      run: |
        echo "Checking service tier definitions..."
        if ! grep -q "SERVICE_TIERS" src/constants/index.ts; then
          echo "ERROR: Service tier definitions missing"
          exit 1
        fi
        echo "✅ Service boundaries defined"
    
    - name: Validate Evidence Protocol
      run: |
        echo "Checking evidence validation components..."
        if ! grep -q "EvidenceValidator" src/components/evidence-protocol/EvidenceValidator.tsx; then
          echo "ERROR: Evidence validation protocol missing"
          exit 1
        fi
        echo "✅ Evidence protocol implemented"
    
    - name: Validate Professional Standards
      run: |
        echo "Checking for business optimization focus..."
        # Check for prohibited terms that violate professional standards
        if grep -r -i "get rich\|guaranteed returns\|no risk" src/; then
          echo "ERROR: Unprofessional language detected"
          exit 1
        fi
        echo "✅ Professional standards maintained"
    
    - name: Validate Quality Assurance
      run: |
        echo "Checking quality monitoring components..."
        if ! grep -q "QualityDashboard" src/components/quality-assurance/QualityDashboard.tsx; then
          echo "ERROR: Quality assurance monitoring missing"
          exit 1
        fi
        echo "✅ Quality assurance implemented"
    
    - name: Constitutional Compliance Report
      run: |
        echo "======================================"
        echo "Constitutional Compliance Report"
        echo "======================================"
        echo "Service Boundaries: ✅ Enforced"
        echo "Evidence Protocol: ✅ Required"
        echo "Professional Standards: ✅ Maintained"
        echo "Quality Assurance: ✅ Monitored"
        echo "======================================"
        echo "Overall Status: COMPLIANT"
        echo "======================================"
    
    - name: Upload compliance report
      uses: actions/upload-artifact@v3
      with:
        name: constitutional-compliance-report
        path: |
          build/
          src/types/
          src/constants/